import type { Metadata } from "next";
import "./globals.css";
import { ExecutionProvider } from "@/context/ExecutionContext";

export const metadata: Metadata = {
  title: "CrewAI Studio: Design & Build Autonomous Crews",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <ExecutionProvider>
          {children}
        </ExecutionProvider>
      </body>
    </html>
  );
}
