import type { Metadata } from "next";
import "./globals.css";
import { ExecutionProvider } from "@/context/ExecutionContext";
import { SettingsProvider } from "@/context/SettingsContext";

export const metadata: Metadata = {
  title: "CrewAI Studio: Design & Build Autonomous Crews",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <SettingsProvider>
          <ExecutionProvider>
            {children}
          </ExecutionProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
